name: Release

on:
  push:
    branches:
      - feat/semantic-release

jobs:
  release:
    runs-on: ubuntu-latest
    container: 
      image: node:8.17.0-stretch # Node 8 + Debian 9 (incluye Python 2.7)
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar Node.js y Python
        run: |
          node -v # Debe mostrar v8.17.0
          python --version # Debe mostrar Python 2.7.x

      - name: Instalar dependencias
        run: |
          npm ci

      - name: Ejecutar Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
