name: Release

on:
  push:
    branches:
      - feat/semantic-release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js 8.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 8.17.0

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release (v17)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release@17
